### PR TITLE
Backend 96percent complete

### PR DESCRIPTION
**Pull request by ChinyangaTL**
Awaiting your comments on your thoughts so far.

All routes complete for authentication and for the journal entries.

There still remains a few little niggles we shall discuss on a call about the error handling.

### CODE REVIEW

**Comment by optimusinhisprime** [comment]
Happy with code so far. What do you think about adding collections, where a user can store their thoughts onto different collections for example have a collection that they only talk about business in? Daily summary collection? Or have predefined tags they can select for an entry. Business,relationship,daily summary,other that kind of stuff.

**Comment by loitijoseph** [comment]
Awesome.

I was thinking maybe we can add how someone was feeling when they were doing the entry so that we can do filter with emotions as an improvement to our project. I have a feeling we are going to be asked that...

**Comment by ChinyangaTL** [comment]
Yeah, as discussed during the call last night I'll add some enums to represent something like that.

Take a look at the figma file for an idea of how it we might do it on the client.

**Comment by loitijoseph** [comment]
> Yeah, as discussed during the call last night I'll add some enums to represent something like that.
> 
> Take a look at the figma file for an idea of how it we might do it on the client.

Awesome, I saw that, don't forget to filter using the emotions if we have time. That's cool

**Pull request merged**
