### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ChinyangaTL**
Merge conflicts imminent. Will be dealt with.

Close to 99 percent product completion.
Frontend CRUD operations all successfully making requests to the backend.
Frontend styled, along with client side form validation.

### CODE REVIEW

**Comment by ChinyangaTL** [comment]
Thank you @iseeflames, slight oversight on my part.

**Comment by ChinyangaTL** [comment]
@loitijoseph just make your review and when you're done at @rmoswela so he can merge to main.

**Comment by loitijoseph** [comment]
I'm done @ChinyangaTL. You can merge.

@rmoswela Please merge.

**Review by loitijoseph — APPROVED** [review]
Good to go.

**Comment by rmoswela** [comment]
commit messages still a problem i see :-(

**Pull request merged**
